import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  route("auth/login", "routes/auth-login.tsx"),
  route("auth/forgot-password", "routes/auth-forgot-password.tsx"),
  route("auth/reset-password", "routes/auth-reset-password.tsx"),
  route("auth/signup", "routes/auth-signup.tsx"),
  route("auth/verify-email", "routes/auth-verify-email.tsx"),
  index("routes/home.tsx"),
  route("accounts", "routes/accounts.tsx"),
  route("accounts/:accountId", "routes/account-detail.tsx"),
  route("categories", "routes/categories.tsx"),
  route("categories/:categoryId", "routes/category-detail.tsx"),
  route("debts", "routes/debts.tsx"),
  route("debts/:debtId", "routes/debt-detail.tsx"),
  route("chat-integrations/telegram/link", "routes/telegram-dev-link.tsx"),
  route("foundation", "routes/foundation.tsx"),
  route("imports", "routes/import-documents.tsx"),
  route("imports/upload", "routes/import-upload.tsx"),
  route("imports/documents/:documentId", "routes/import-document-detail.tsx"),
  route("imports/documents/:documentId/mapping", "routes/import-mapping.tsx"),
  route(
    "imports/documents/:documentId/mapping/visual",
    "routes/import-coordinate-mapping.tsx",
  ),
  route("imports/documents/:documentId/review", "routes/import-review.tsx"),
  route("ledger/manual", "routes/manual-ledger.tsx"),
  route("operations", "routes/operations.tsx"),
  route("properties", "routes/properties.tsx"),
  route("profile", "routes/profile.tsx"),
  route("profile/account", "routes/profile-account.tsx"),
  route("profile/security", "routes/profile-security.tsx"),
  route("profile/sessions", "routes/profile-sessions.tsx"),
  route("reports", "routes/reports.tsx"),
  route("rules", "routes/transaction-rules.tsx"),
  route("workspaces", "routes/workspaces.tsx"),
  route("workspaces/invitation", "routes/workspace-invitation.tsx"),
  route("workspaces/:workspaceId/settings", "routes/workspace-settings.tsx"),
  route("workspaces/:workspaceId/activity", "routes/workspace-activity.tsx"),
] satisfies RouteConfig;
