from datetime import timedelta

CHAT_REVIEW_ACTION_TTL = timedelta(minutes=30)
CHAT_REVIEW_CATEGORY_PAGE_SIZE = 7
CHAT_REVIEW_PROPERTY_MAX_CHOICES = 8
CHAT_REVIEW_TRANSFER_ACCOUNT_MAX_CHOICES = 8
CHAT_REVIEW_TRANSFER_PAIR_MAX_CHOICES = 5
